/*
	Things to add:
	
*/

let gameData = [
  {
    title: ".detuned",
    yearReleased: 2009,
    myRating: 3,
    gameConsole: ["ps3"],
  },
  {
    title: "#IDARB",
    yearReleased: 2015,
    myRating: 5,
    gameConsole: ["xb1"],
  },
  {
    title: "10 Second Ninja X",
    yearReleased: 2016,
    myRating: 6,
    gameConsole: ["xb1"],
  },
  {
    title: "A Dinosaur's Tale",
    yearReleased: 1994,
    myRating: 5,
    gameConsole: ["gen"],
  },
  {
    title: "A Memoir Blue",
    yearReleased: 2022,
    myRating: 6,
    gameConsole: ["xsx"],
  },
  {
    title: "A Short Hike",
    yearReleased: 2019,
    myRating: 9,
    gameConsole: ["xsx"],
  },
  {
    title: "ABZU",
    yearReleased: 2016,
    myRating: 6,
    gameConsole: ["ps4"],
  },
  {
    title: "Afrika",
    yearReleased: 2008,
    myRating: 8,
    gameConsole: ["ps3"],
  },
  {
    title: "Altered Beast",
    yearReleased: 1988,
    myRating: 4,
    gameConsole: ["gen"],
  },
  {
    title: "Alto's Adventure",
    yearReleased: 2015,
    myRating: 8,
    gameConsole: ["ios"],
  },
  {
    title: "Animal Crossing New Horizons",
    yearReleased: 2020,
    myRating: 7,
    gameConsole: ["ns"],
  },
  {
    title: "Assassin's Creed Odyssey",
    yearReleased: 2012,
    myRating: 9,
    gameConsole: ["xb1"],
  },
  {
    title: "Assassin's Creed Origins",
    yearReleased: 2009,
    myRating: 8,
    gameConsole: ["xb1"],
  },
  {
    title: "Backyard Baseball",
    yearReleased: 1997,
    myRating: 8,
    gameConsole: ["gbasp"],
  },
  {
    title: "Backyard Football",
    yearReleased: 1999,
    myRating: 7,
    gameConsole: ["gbasp"],
  },
  {
    title: "Banjo-Kazooie",
    yearReleased: 1998,
    myRating: 7,
    gameConsole: ["xb1"],
  },
  {
    title: "Banjo-Tooie",
    yearReleased: 2000,
    myRating: 7,
    gameConsole: ["xb1"],
  },
  {
    title: "Battleblock Theater",
    yearReleased: 2013,
    myRating: 6,
    gameConsole: ["pc"],
  },
  {
    title: "Beat Saber",
    yearReleased: 2018,
    myRating: 10,
    gameConsole: ["mq"],
  },
  {
    title: "Borderlands",
    yearReleased: 2009,
    myRating: 7,
    gameConsole: ["x360"],
  },
  {
    title: "Braid",
    yearReleased: 2008,
    myRating: 6,
    gameConsole: ["pc", "x360"],
  },
  {
    title: "Brothers: A Tale of Two Sons",
    yearReleased: 2013,
    myRating: 9,
    gameConsole: ["xb1"],
  },
  {
    title: "Calculator: The Game",
    yearReleased: 2017,
    myRating: 7,
    gameConsole: ["ios"],
  },
  {
    title: "Call of Duty: Black Ops",
    yearReleased: 2010,
    myRating: 7,
    gameConsole: ["x360"],
  },
  {
    title: "Call of Duty: Modern Warfare 2",
    yearReleased: 2009,
    myRating: 7,
    gameConsole: ["ps3"],
  },
  {
    title: "Call of the Sea",
    yearReleased: 2020,
    myRating: 9,
    gameConsole: ["xb1"],
  },
  {
    title: "Card City Nights",
    yearReleased: 2014,
    myRating: 7,
    gameConsole: ["pc"],
  },
  {
    title: "Castlevania: Dawn of Sorrow",
    yearReleased: 2005,
    myRating: 6,
    gameConsole: ["ds"],
  },
  {
    title: "Condemned: Criminal Origins",
    yearReleased: 2005,
    myRating: 6,
    gameConsole: ["x360"],
  },
  {
    title: "CTR: Crash Team Racing",
    yearReleased: 1999,
    myRating: 6,
    gameConsole: ["ps1"],
  },
  {
    title: "Dance Dance Revolution Mario Mix",
    yearReleased: 2005,
    myRating: 8,
    gameConsole: ["gc"],
  },
  {
    title: "Day of the Tentacle Remastered",
    yearReleased: 1993,
    myRating: 8,
    gameConsole: ["ps4", "xb1"],
  },
  {
    title: "Dead Space",
    yearReleased: 2008,
    myRating: 8,
    gameConsole: ["ps3"],
  },
  {
    title: "Deadstorm Pirates 4D",
    yearReleased: 2010,
    myRating: 6,
    gameConsole: ["arcade"],
  },
  {
    title: "Dear Esther",
    yearReleased: 2012,
    myRating: 6,
    gameConsole: ["pc", "xsx"],
  },
  {
    title: "Donut Country",
    yearReleased: 2018,
    myRating: 7,
    gameConsole: ["xb1"],
  },
  {
    title: "Down the Rabbit Hole",
    yearReleased: 2020,
    myRating: 9,
    gameConsole: ["mq"],
  },
  {
    title: "Elite Beat Agents",
    yearReleased: 2006,
    myRating: 7,
    gameConsole: ["ds"],
  },
  {
    title: "Fable",
    yearReleased: 2004,
    myRating: 7,
    gameConsole: ["xbox"],
  },
  {
    title: "Fez",
    yearReleased: 2012,
    myRating: 7,
    gameConsole: ["pc"],
  },
  {
    title: "Fire Emblem",
    yearReleased: 2003,
    myRating: 7,
    gameConsole: ["gbasp"],
  },
  {
    title: "Firewatch",
    yearReleased: 2016,
    myRating: 9,
    gameConsole: ["xb1"],
  },
  {
    title: "Flower",
    yearReleased: 2009,
    myRating: 7,
    gameConsole: ["ps3"],
  },
  {
    title: "Forza Horizon 5",
    yearReleased: 2021,
    myRating: 9,
    gameConsole: ["xsx"],
  },
  {
    title: "Fractured Minds",
    yearReleased: 2017,
    myRating: 4,
    gameConsole: ["xb1"],
  },
  {
    title: "Freddi Fish 3: The Case of the Stolen Conch Shell",
    yearReleased: 1998,
    myRating: 5,
    gameConsole: ["pc"],
  },
  {
    title: "Frogger Returns",
    yearReleased: 2009,
    myRating: 5,
    gameConsole: ["ps3"],
  },
  {
    title: "Game Dev Tycoon",
    yearReleased: 2012,
    myRating: 6,
    gameConsole: ["pc"],
  },
  {
    title: "Garden of the Sea",
    yearReleased: 2022,
    myRating: 8,
    gameConsole: ["mq"],
  },
  {
    title: "Gears of War",
    yearReleased: 2006,
    myRating: 8,
    gameConsole: ["x360", "xb1"],
  },
  {
    title: "GoldenEye 007",
    yearReleased: 1997,
    myRating: 6,
    gameConsole: ["n64"],
  },
  {
    title: "GoldenEye: Rogue Agent",
    yearReleased: 2004,
    myRating: 7,
    gameConsole: ["gc"],
  },
  {
    title: "Golf Peaks",
    yearReleased: 2018,
    myRating: 7,
    gameConsole: ["ios"],
  },
  {
    title: "Golf Story",
    yearReleased: 2017,
    myRating: 9,
    gameConsole: ["ns"],
  },
  {
    title: "Gone Home",
    yearReleased: 2013,
    myRating: 8,
    gameConsole: ["xb1", "pc"],
  },
  {
    title: "Guacamelee!: Super Turbo Championship Edition",
    yearReleased: 2013,
    myRating: 6,
    gameConsole: ["xb1"],
  },
  {
    title: "Guitar Hero III: Legends of Rock",
    yearReleased: 2007,
    myRating: 7,
    gameConsole: ["ps3"],
  },
  {
    title: "Halo 2",
    yearReleased: 2004,
    myRating: 9,
    gameConsole: ["xbox", "x360", "xb1"],
  },
  {
    title: "Halo 3",
    yearReleased: 2007,
    myRating: 9,
    gameConsole: ["x360", "xb1"],
  },
  {
    title: "Halo 3: ODST",
    yearReleased: 2009,
    myRating: 6,
    gameConsole: ["x360", "xb1"],
  },
  {
    title: "Halo 4",
    yearReleased: 2012,
    myRating: 7,
    gameConsole: ["xb1"],
  },
  {
    title: "Halo: Combat Evolved",
    yearReleased: 2001,
    myRating: 7,
    gameConsole: ["xbox", "x360"],
  },
  {
    title: "Halo: Combat Evolved Anniversary",
    yearReleased: 2011,
    myRating: 7,
    gameConsole: ["xb1"],
  },
  {
    title: "Halo: Reach",
    yearReleased: 2010,
    myRating: 6,
    gameConsole: ["x360"],
  },
  {
    title: "Harry Potter and the Prisoner of Azkaban GBA",
    yearReleased: 2004,
    myRating: 8,
    gameConsole: ["gbasp"],
  },
  {
    title: "Harry Potter and the Prisoner of Azkaban",
    yearReleased: 2004,
    myRating: 8,
    gameConsole: ["gc"],
  },
  {
    title: "Harry Potter and the Sorcerer's Stone",
    yearReleased: 2001,
    myRating: 7,
    gameConsole: ["ps1"],
  },
  {
    title: "Her Story",
    yearReleased: 2015,
    myRating: 6,
    gameConsole: ["pc"],
  },
  {
    title: "Hidden Through Time",
    yearReleased: 2020,
    myRating: 6,
    gameConsole: ["xb1"],
  },
  {
    title: "Home",
    yearReleased: 2012,
    myRating: 7,
    gameConsole: ["pc"],
  },
  {
    title: "Homefront",
    yearReleased: 2011,
    myRating: 5,
    gameConsole: ["ps3"],
  },
  {
    title: "Hook",
    yearReleased: 2015,
    myRating: 7,
    gameConsole: ["pc"],
  },
  {
    title: "Hue",
    yearReleased: 2016,
    myRating: 6,
    gameConsole: ["xb1"],
  },
  {
    title: "Idle Acorns",
    yearReleased: 2021,
    myRating: 6,
    gameConsole: ["ios"],
  },
  {
    title: "Inside",
    yearReleased: 2016,
    myRating: 10,
    gameConsole: ["pc", "xb1"],
  },
  {
    title: "It Takes Two",
    yearReleased: 2021,
    myRating: 10,
    gameConsole: ["xsx"],
  },
  {
    title: "Jetpack Joyride",
    yearReleased: 2011,
    myRating: 7,
    gameConsole: ["ps3"],
  },
  {
    title: "Just Dance 2020",
    yearReleased: 2019,
    myRating: 8,
    gameConsole: ["ns"],
  },
  {
    title: "Kirby's Pinball Land",
    yearReleased: 1993,
    myRating: 7,
    gameConsole: ["gbasp"],
  },
  {
    title: "Kitty Letter",
    yearReleased: 2021,
    myRating: 7,
    gameConsole: ["ios"],
  },
  {
    title: "Late Shift",
    yearReleased: 2016,
    myRating: 6,
    gameConsole: ["xb1"],
  },
  {
    title: "Left 4 Dead",
    yearReleased: 2008,
    myRating: 8,
    gameConsole: ["x360", "pc"],
  },
  {
    title: "Left 4 Dead 2",
    yearReleased: 2009,
    myRating: 8,
    gameConsole: ["pc"],
  },
  {
    title: "LEGO Harry Potter: Years 1-4",
    yearReleased: 2010,
    myRating: 8,
    gameConsole: ["ps3", "xsx"],
  },
  {
    title: "LEGO Harry Potter: Years 5-7",
    yearReleased: 2011,
    myRating: 8,
    gameConsole: ["ps3"],
  },
  {
    title: "Linger in Shadows",
    yearReleased: 2008,
    myRating: 4,
    gameConsole: ["ps3"],
  },
  {
    title: "Limbo",
    yearReleased: 2010,
    myRating: 10,
    gameConsole: ["x360", "xb1", "ps4", "pc"],
  },
  {
    title: "Little Inferno",
    yearReleased: 2012,
    myRating: 9,
    gameConsole: ["pc"],
  },
  {
    title: "LittleBigPlanet",
    yearReleased: 2008,
    myRating: 8,
    gameConsole: ["ps3"],
  },
  {
    title: "Luigi's Mansion",
    yearReleased: 2001,
    myRating: 6,
    gameConsole: ["gc"],
  },
  {
    title: "Machinarium",
    yearReleased: 2009,
    myRating: 6,
    gameConsole: ["ps3"],
  },
  {
    title: "Manhunt",
    yearReleased: 2003,
    myRating: 6,
    gameConsole: ["ps2"],
  },
  {
    title: "Mario Kart 64",
    yearReleased: 1996,
    myRating: 8,
    gameConsole: ["n64", "wii"],
  },
  {
    title: "Mario Kart 8",
    yearReleased: 2014,
    myRating: 10,
    gameConsole: ["wiiu", "ns"],
  },
  {
    title: "Mario Kart DS",
    yearReleased: 2005,
    myRating: 8,
    gameConsole: ["ds"],
  },
  {
    title: "Mario Kart Super Circuit",
    yearReleased: 2001,
    myRating: 8,
    gameConsole: ["ds"],
  },
  {
    title: "Mario Kart: Double Dash!!",
    yearReleased: 2003,
    myRating: 10,
    gameConsole: ["gc"],
  },
  {
    title: "Max: The Curse of Brotherhood",
    yearReleased: 2013,
    myRating: 7,
    gameConsole: ["xb1"],
  },
  {
    title: "Minecraft",
    yearReleased: 2009,
    myRating: 10,
    gameConsole: ["pc", "xb1"],
  },
  {
    title: "Minesweeper Genius",
    yearReleased: 2019,
    myRating: 8,
    gameConsole: ["xb1"],
  },
  {
    title: "Modern Tales: Age of Invention",
    yearReleased: 2017,
    myRating: 7,
    gameConsole: ["xsx"],
  },
  {
    title: "Monument Valley",
    yearReleased: 2014,
    myRating: 7,
    gameConsole: ["ios"],
  },
  {
    title: "Mortal Kombat",
    yearReleased: 1992,
    myRating: 6,
    gameConsole: ["gen"],
  },
  {
    title: "Mortal Kombat 4",
    yearReleased: 1997,
    myRating: 6,
    gameConsole: ["ps1"],
  },
  {
    title: "Mortal Kombat II",
    yearReleased: 1993,
    myRating: 6,
    gameConsole: ["gen"],
  },
  {
    title: "Mortal Kombat vs. DC Universe",
    yearReleased: 2008,
    myRating: 6,
    gameConsole: ["ps3"],
  },
  {
    title: "Mortal Kombat: Armageddon",
    yearReleased: 2006,
    myRating: 6,
    gameConsole: ["xbox"],
  },
  {
    title: "Mortal Kombat: Deadly Alliance",
    yearReleased: 2002,
    myRating: 6,
    gameConsole: ["gc"],
  },
  {
    title: "Mortal Kombat: Deception",
    yearReleased: 2004,
    myRating: 6,
    gameConsole: ["gc"],
  },
  {
    title: "Moving Out",
    yearReleased: 2020,
    myRating: 8,
    gameConsole: ["xb1"],
  },
  {
    title: "Myst",
    yearReleased: 1993,
    myRating: 8,
    gameConsole: ["mq"],
  },
  {
    title: "Need for Speed: Hot Pursuit 2",
    yearReleased: 2002,
    myRating: 5,
    gameConsole: ["ps2"],
  },
  {
    title: "Never Alone",
    yearReleased: 2014,
    myRating: 7,
    gameConsole: ["xb1"],
  },
  {
    title: "New Pokemon Snap",
    yearReleased: 2021,
    myRating: 7,
    gameConsole: ["ns"],
  },
  {
    title: "New Super Mario Bros.",
    yearReleased: 2006,
    myRating: 8,
    gameConsole: ["ds"],
  },
  {
    title: "Organ Trail",
    yearReleased: 2011,
    myRating: 6,
    gameConsole: ["pc"],
  },
  {
    title: "Ori and the Blind Forest",
    yearReleased: 2015,
    myRating: 9,
    gameConsole: ["xb1"],
  },
  {
    title: "Oxenfree",
    yearReleased: 2016,
    myRating: 8,
    gameConsole: ["xb1"],
  },
  {
    title: "Paperboy",
    yearReleased: 1984,
    myRating: 6,
    gameConsole: ["gen"],
  },
  {
    title: "PAW Patrol Mighty Pups Save Adventure Bay",
    yearReleased: 2020,
    myRating: 5,
    gameConsole: ["xsx"],
  },
  {
    title: "Peggle",
    yearReleased: 2007,
    myRating: 8,
    gameConsole: ["pc", "xb1"],
  },
  {
    title: "Peggle 2",
    yearReleased: 2013,
    myRating: 8,
    gameConsole: ["xb1"],
  },
  {
    title: "Peggle Extreme",
    yearReleased: 2007,
    myRating: 8,
    gameConsole: ["pc"],
  },
  {
    title: "Peggle Nights",
    yearReleased: 2008,
    myRating: 8,
    gameConsole: ["pc"],
  },
  {
    title: "Peggle: World of Warcraft Edition",
    yearReleased: 2007,
    myRating: 8,
    gameConsole: ["pc"],
  },
  {
    title: "Plants vs. Zombies",
    yearReleased: 2009,
    myRating: 7,
    gameConsole: ["pc"],
  },
  {
    title: "Pokemon Blue Version",
    yearReleased: 1996,
    myRating: 7,
    gameConsole: ["gbc", "gbasp", "ds"],
  },
  {
    title: "Pokemon Crystal Version",
    yearReleased: 2000,
    myRating: 7,
    gameConsole: ["gbc", "gbasp"],
  },
  {
    title: "Pokemon FireRed Version",
    yearReleased: 2004,
    myRating: 7,
    gameConsole: ["gbasp"],
  },
  {
    title: "Pokemon Gold Version",
    yearReleased: 1999,
    myRating: 7,
    gameConsole: ["gbc", "gbasp"],
  },
  {
    title: "Pokemon Lets Go Eevee",
    yearReleased: 2013,
    myRating: 8,
    gameConsole: ["ns"],
  },
  {
    title: "Pokemon Pinball",
    yearReleased: 1999,
    myRating: 6,
    gameConsole: ["gbc", "gbasp"],
  },
  {
    title: "Pokemon Puzzle League",
    yearReleased: 2000,
    myRating: 6,
    gameConsole: ["ns"],
  },
  {
    title: "Pokemon Quest",
    yearReleased: 2018,
    myRating: 6,
    gameConsole: ["ns"],
  },
  {
    title: "Pokemon Red Version",
    yearReleased: 1996,
    myRating: 7,
    gameConsole: ["gbc", "gbasp"],
  },
  {
    title: "Pokemon Ruby Version",
    yearReleased: 2002,
    myRating: 6,
    gameConsole: ["gbasp"],
  },
  {
    title: "Pokemon Silver Version",
    yearReleased: 1999,
    myRating: 7,
    gameConsole: ["gbc", "gbasp"],
  },
  {
    title: "Pokemon Snap",
    yearReleased: 1999,
    myRating: 7,
    gameConsole: ["wii", "ns"],
  },
  {
    title: "Polarity",
    yearReleased: 2007,
    myRating: 6,
    gameConsole: ["pc"],
  },
  {
    title: "Portal",
    yearReleased: 2007,
    myRating: 10,
    gameConsole: ["pc", "xb1"],
  },
  {
    title: "Portal 2",
    yearReleased: 2011,
    myRating: 10,
    gameConsole: ["pc", "x360", "xb1"],
  },
  {
    title: "Progress (to 100)",
    yearReleased: 2015,
    myRating: 8,
    gameConsole: ["ios"],
  },
  {
    title: "Q.U.B.E. 2",
    yearReleased: 2018,
    myRating: 7,
    gameConsole: ["xb1"],
  },
  {
    title: "Rain On Your Parade",
    yearReleased: 2021,
    myRating: 7,
    gameConsole: ["xb1"],
  },
  {
    title: "Red Matter",
    yearReleased: 2018,
    myRating: 8,
    gameConsole: ["mq"],
  },
  {
    title: "Refunct",
    yearReleased: 2015,
    myRating: 9,
    gameConsole: ["pc", "ns", "xb1"],
  },
  {
    title: "Resident Evil",
    yearReleased: 1996,
    myRating: 5,
    gameConsole: ["ps1"],
  },
  {
    title: "Resident Evil 3",
    yearReleased: 2020,
    myRating: 7,
    gameConsole: ["xsx"],
  },
  {
    title: "Resident Evil 3: Nemesis",
    yearReleased: 1999,
    myRating: 6,
    gameConsole: ["ps1"],
  },
  {
    title: "Resident Evil 4",
    yearReleased: 2005,
    myRating: 7,
    gameConsole: ["gc", "ps2"],
  },
  {
    title: "Resident Evil: Dead Aim",
    yearReleased: 2003,
    myRating: 5,
    gameConsole: ["ps2"],
  },
  {
    title: "Resident Evil: Deadly Silence",
    yearReleased: 2006,
    myRating: 6,
    gameConsole: ["ds"],
  },
  {
    title: "Resident Evil: The Umbrella Chronicles",
    yearReleased: 2007,
    myRating: 5,
    gameConsole: ["wii"],
  },
  {
    title: "Resistance: Fall of Man",
    yearReleased: 2006,
    myRating: 5,
    gameConsole: ["ps3"],
  },
  {
    title: "Rise of the Tomb Raider",
    yearReleased: 2015,
    myRating: 7,
    gameConsole: ["xb1"],
  },
  {
    title: "Rituals",
    yearReleased: 2015,
    myRating: 4,
    gameConsole: ["pc"],
  },
  {
    title: "Road Rash",
    yearReleased: 1991,
    myRating: 6,
    gameConsole: ["gen"],
  },
  {
    title: "Rugrats in Paris: The Movie",
    yearReleased: 2000,
    myRating: 6,
    gameConsole: ["ps1"],
  },
  {
    title: "Rusty Lake Hotel",
    yearReleased: 2015,
    myRating: 7,
    gameConsole: ["pc"],
  },
  {
    title: "Rusty Lake: Roots",
    yearReleased: 2016,
    myRating: 7,
    gameConsole: ["pc"],
  },
  {
    title: "Scribblenauts Unlimited",
    yearReleased: 2012,
    myRating: 7,
    gameConsole: ["pc"],
  },
  {
    title: "Shadow of the Colossus",
    yearReleased: 2005,
    myRating: 8,
    gameConsole: ["ps3"],
  },
  {
    title: "Snipperclips Plus",
    yearReleased: 2017,
    myRating: 7,
    gameConsole: ["ns"],
  },
  {
    title: "Slayaway Camp",
    yearReleased: 2016,
    myRating: 8,
    gameConsole: ["pc", "xb1"],
  },
  {
    title: "Slime Rancher",
    yearReleased: 2017,
    myRating: 9,
    gameConsole: ["xb1"],
  },
  {
    title: "Sonic Adventure 2: Battle",
    yearReleased: 2001,
    myRating: 7,
    gameConsole: ["gc"],
  },
  {
    title: "South Park: The Stick of Truth",
    yearReleased: 2014,
    myRating: 7,
    gameConsole: ["pc"],
  },
  {
    title: "SpeedRunners",
    yearReleased: 2016,
    myRating: 7,
    gameConsole: ["pc", "xb1"],
  },
  {
    title: "Spyro 2: Ripto's Rage!",
    yearReleased: 1999,
    myRating: 7,
    gameConsole: ["ps1", "ps3", "xb1"],
  },
  {
    title: "Spyro the Dragon",
    yearReleased: 1998,
    myRating: 7,
    gameConsole: ["ps1", "ps3", "xb1"],
  },
  {
    title: "Stardew Valley",
    yearReleased: 2016,
    myRating: 10,
    gameConsole: ["pc"],
  },
  {
    title: "Steamworld Dig 2",
    yearReleased: 2017,
    myRating: 7,
    gameConsole: ["xb1"],
  },
  {
    title: "Stranger Things: The Game",
    yearReleased: 2017,
    myRating: 6,
    gameConsole: ["ios"],
  },
  {
    title: "Street Fighter II",
    yearReleased: 1991,
    myRating: 6,
    gameConsole: ["snes"],
  },
  {
    title: "Stubbs the Zombie in Rebel Without a Pulse",
    yearReleased: 2005,
    myRating: 6,
    gameConsole: ["xbox"],
  },
  {
    title: "Super Mario 64",
    yearReleased: 1996,
    myRating: 9,
    gameConsole: ["n64", "wii", "ns"],
  },
  {
    title: "Super Mario 64 DS",
    yearReleased: 2004,
    myRating: 9,
    gameConsole: ["ds"],
  },
  {
    title: "Super Mario Bros.",
    yearReleased: 1985,
    myRating: 6,
    gameConsole: ["nes"],
  },
  {
    title: "Super Mario Bros. Deluxe",
    yearReleased: 1999,
    myRating: 7,
    gameConsole: ["gbc", "gbasp"],
  },
  {
    title: "Super Mario Kart",
    yearReleased: 1992,
    myRating: 6,
    gameConsole: ["snes"],
  },
  {
    title: "Super Mario Odyssey",
    yearReleased: 2017,
    myRating: 9,
    gameConsole: ["ns"],
  },
  {
    title: "Super Mario Party",
    yearReleased: 2018,
    myRating: 7,
    gameConsole: ["ns"],
  },
  {
    title: "Super Mario Run",
    yearReleased: 2016,
    myRating: 7,
    gameConsole: ["ios"],
  },
  {
    title: "Super Mario Sunshine",
    yearReleased: 2002,
    myRating: 9,
    gameConsole: ["gc", "ns"],
  },
  {
    title: "Super Mario World",
    yearReleased: 1990,
    myRating: 10,
    gameConsole: ["snes"],
  },
  {
    title: "Super Mario World: Super Mario Advance 2",
    yearReleased: 2001,
    myRating: 10,
    gameConsole: ["gbasp"],
  },
  {
    title: "Super Meat Boy",
    yearReleased: 2010,
    myRating: 8,
    gameConsole: ["x360", "xb1"],
  },
  {
    title: "Super Mega Baseball: Extra Innings",
    yearReleased: 2014,
    myRating: 7,
    gameConsole: ["xb1"],
  },
  {
    title: "Super Smash Bros.",
    yearReleased: 1999,
    myRating: 7,
    gameConsole: ["n64", "wii"],
  },
  {
    title: "Super Smash Bros.: Brawl",
    yearReleased: 2008,
    myRating: 6,
    gameConsole: ["wii"],
  },
  {
    title: "Super Smash Bros.: Melee",
    yearReleased: 2001,
    myRating: 9,
    gameConsole: ["gc"],
  },
  {
    title: "Superhot",
    yearReleased: 2016,
    myRating: 8,
    gameConsole: ["xb1"],
  },
  {
    title: "Superhot: Mind Control Delete",
    yearReleased: 2020,
    myRating: 6,
    gameConsole: ["xsx"],
  },
  {
    title: "Superliminal",
    yearReleased: 2019,
    myRating: 8,
    gameConsole: ["xb1"],
  },
  {
    title: "Tales from the Borderlands",
    yearReleased: 2014,
    myRating: 7,
    gameConsole: ["xb1"],
  },
  {
    title: "Teenage Mutant Ninja Turtles",
    yearReleased: 1989,
    myRating: 5,
    gameConsole: ["arcade"],
  },
  {
    title: "Teenage Mutant Ninja Turtles: Turtles in Time",
    yearReleased: 1991,
    myRating: 5,
    gameConsole: ["snes"],
  },
  {
    title: "Terminator: Salvation",
    yearReleased: 2009,
    myRating: 3,
    gameConsole: ["ps3"],
  },
  {
    title: "Tetris Effect: Connected",
    yearReleased: 2018,
    myRating: 7,
    gameConsole: ["xb1"],
  },
  {
    title: "The Artful Escape",
    yearReleased: 2021,
    myRating: 8,
    gameConsole: ["xsx"],
  },
  {
    title: "The Cave",
    yearReleased: 2013,
    myRating: 7,
    gameConsole: ["pc", "xb1"],
  },
  {
    title: "The House of the Dead",
    yearReleased: 1996,
    myRating: 6,
    gameConsole: ["arcade"],
  },
  {
    title: "The Legend of Zelda: Ocarina of Time",
    yearReleased: 1998,
    myRating: 6,
    gameConsole: ["n64"],
  },
  {
    title: "The LEGO Movie Videogame",
    yearReleased: 2014,
    myRating: 7,
    gameConsole: ["xb1"],
  },
  {
    title: "The Park",
    yearReleased: 2015,
    myRating: 6,
    gameConsole: ["xb1"],
  },
  {
    title: "The Plan",
    yearReleased: 2013,
    myRating: 5,
    gameConsole: ["pc"],
  },
  {
    title: "The Room",
    yearReleased: 2012,
    myRating: 6,
    gameConsole: ["pc"],
  },
  {
    title: "The Room Two",
    yearReleased: 2013,
    myRating: 6,
    gameConsole: ["pc"],
  },
  {
    title: "The Room VR",
    yearReleased: 2020,
    myRating: 9,
    gameConsole: ["mq"],
  },
  {
    title: "The Simpsons",
    yearReleased: 1991,
    myRating: 5,
    gameConsole: ["ps3"],
  },
  {
    title: "The Stanley Parable: Ultra Deluxe",
    yearReleased: 2022,
    myRating: 9,
    gameConsole: ["xsx"],
  },
  {
    title: "The Touryst",
    yearReleased: 2019,
    myRating: 7,
    gameConsole: ["xb1"],
  },
  {
    title: "The Witness",
    yearReleased: 2016,
    myRating: 7,
    gameConsole: ["xb1"],
  },
  {
    title: "Thirty Flights of Loving",
    yearReleased: 2012,
    myRating: 5,
    gameConsole: ["pc"],
  },
  {
    title: "Thomas Was Alone",
    yearReleased: 2012,
    myRating: 9,
    gameConsole: ["pc", "xb1"],
  },
  {
    title: "Thrill of the Fight",
    yearReleased: 2016,
    myRating: 8,
    gameConsole: ["mq"],
  },
  {
    title: "TimeSplitters: Future Perfect",
    yearReleased: 2005,
    myRating: 7,
    gameConsole: ["ps2"],
  },
  {
    title: "Tiny Toon Adventures: Acme All-Stars",
    yearReleased: 1994,
    myRating: 8,
    gameConsole: ["gen"],
  },
  {
    title: "Tomb Raider: Definitive Edition",
    yearReleased: 2014,
    myRating: 8,
    gameConsole: ["xb1"],
  },
  {
    title: "Tony Hawk's Pro Skater",
    yearReleased: 1999,
    myRating: 7,
    gameConsole: ["ps1", "xb1"],
  },
  {
    title: "Tony Hawk's Pro Skater 2",
    yearReleased: 2000,
    myRating: 7,
    gameConsole: ["xb1"],
  },
  {
    title: "Tony Hawk's Pro Skater 3",
    yearReleased: 2001,
    myRating: 6,
    gameConsole: ["gc"],
  },
  {
    title: "Twelve Minutes",
    yearReleased: 2021,
    myRating: 7,
    gameConsole: ["xsx"],
  },
  {
    title: "Twisted Metal 2",
    yearReleased: 1996,
    myRating: 5,
    gameConsole: ["ps1"],
  },
  {
    title: "Uncharted 2: Among Thieves",
    yearReleased: 2009,
    myRating: 10,
    gameConsole: ["ps3", "ps4"],
  },
  {
    title: "Uncharted 3: Drake's Deception",
    yearReleased: 2011,
    myRating: 10,
    gameConsole: ["ps3", "ps4"],
  },
  {
    title: "Uncharted 4 PS4",
    yearReleased: 2016,
    myRating: 10,
    gameConsole: ["ps4"],
  },
  {
    title: "Uncharted: Drake's Fortune",
    yearReleased: 2007,
    myRating: 10,
    gameConsole: ["ps3", "ps4"],
  },
  {
    title: "Unpacking",
    yearReleased: 2021,
    myRating: 8,
    gameConsole: ["xsx"],
  },
  {
    title: "Untitled Goose Game",
    yearReleased: 2019,
    myRating: 9,
    gameConsole: ["xb1"],
  },
  {
    title: "Vectorman",
    yearReleased: 1995,
    myRating: 4,
    gameConsole: ["gen"],
  },
  {
    title: "Virtua Fighter 5: Final Showdown",
    yearReleased: 2010,
    myRating: 4,
    gameConsole: ["xb1"],
  },
  {
    title: "Virtual Virtual Reality",
    yearReleased: 2017,
    myRating: 8,
    gameConsole: ["mq"],
  },
  {
    title: "Voodoo Vince: Remastered",
    yearReleased: 2003,
    myRating: 6,
    gameConsole: ["xb1"],
  },
  {
    title: "Walkabout Mini Golf",
    yearReleased: 2020,
    myRating: 10,
    gameConsole: ["mq"],
  },
  {
    title: "WarioWare, Inc.: Mega Microgames!",
    yearReleased: 2003,
    myRating: 6,
    gameConsole: ["ns"],
  },
  {
    title: "WarioWare: Touched!",
    yearReleased: 2004,
    myRating: 7,
    gameConsole: ["ds"],
  },
  {
    title: "What Remains of Edith Finch",
    yearReleased: 2017,
    myRating: 9,
    gameConsole: ["xb1"],
  },
  {
    title: "Wizorb",
    yearReleased: 2011,
    myRating: 7,
    gameConsole: ["pc"],
  },
  {
    title: "Wolfenstein",
    yearReleased: 2009,
    myRating: 6,
    gameConsole: ["ps3"],
  },
  {
    title: "Yu-Gi-Oh! Dark Duel Stories",
    yearReleased: 2002,
    myRating: 5,
    gameConsole: ["gbc"],
  },
  {
    title: "Yu-Gi-Oh! The Eternal Duelist Soul",
    yearReleased: 2001,
    myRating: 7,
    gameConsole: ["gbasp"],
  },
  {
    title: "Yu-Gi-Oh! The Falsebound Kingdom",
    yearReleased: 2002,
    myRating: 5,
    gameConsole: ["gc"],
  },
  {
    title: "Yu-Gi-Oh! The Sacred Cards",
    yearReleased: 2003,
    myRating: 7,
    gameConsole: ["gbasp"],
  },
  {
    title: "Yu-Gi-Oh!: Forbidden Memories",
    yearReleased: 1999,
    myRating: 5,
    gameConsole: ["ps2"],
  },
  {
    title: "Yu-Gi-Oh!: The Duelists of the Roses",
    yearReleased: 2001,
    myRating: 9,
    gameConsole: ["ps2"],
  },
];
